#!/usr/bin/env python3
"""Fix demoEffects.ts and append helper functions to scoring.ts.

1. Rewrite sim/data/demoEffects.ts from scratch with all 17 entries
   carrying the new expanded-metadata fields.
2. Append `generateDemoSummary` + `compatibleEffects` + a new
   `DevelopmentTimeResult` shape to sim/domain/scoring.ts.
"""

import sys
from pathlib import Path

# ============================================================================
# Step 1: rewrite demoEffects.ts
# ============================================================================

EFFECTS_SRC = '''/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * DEMO_EFFECTS catalogue — moved verbatim from src/data.ts.
 * Static lookup of effect complexity / cost params; pure data only.
 *
 * Each entry now carries the expanded metadata the new scoring engine
 * needs: `complexity`, `visualImpact`, `compatiblePlatforms`,
 * `synergyTags`, and `researchRequired`.
 */

import { DemoEffect, EraId, PlatformId } from "@packages/types";

/** A shorthand: "every modern PC platform" for shader-era effects. */
const PC_DAWN_PLUS: PlatformId[] = [
  PlatformId.PC_386,
  PlatformId.PC_486,
  PlatformId.PC_PENTIUM,
  PlatformId.PC_PENTIUM_II,
  PlatformId.PC_PENTIUM_III,
];
const PC_PENTIUM_PLUS: PlatformId[] = [
  PlatformId.PC_PENTIUM,
  PlatformId.PC_PENTIUM_II,
  PlatformId.PC_PENTIUM_III,
];
const PC_PII_PLUS: PlatformId[] = [PlatformId.PC_PENTIUM_II, PlatformId.PC_PENTIUM_III];
const PC_PIII: PlatformId[] = [PlatformId.PC_PENTIUM_III];
const AMIGA_ALL: PlatformId[] = [PlatformId.AMIGA_500, PlatformId.AMIGA_1200];
const AMIGA_ST: PlatformId[] = [PlatformId.AMIGA_500, PlatformId.AMIGA_1200, PlatformId.ATARI_ST];
const C64_ZX: PlatformId[] = [PlatformId.C64, PlatformId.ZX_SPECTRUM];

export const DEMO_EFFECTS: DemoEffect[] = [
  // --- 8-BIT ERA ---
  {
    id: "raster_bars",
    name: "Raster Bars / Copper Bars",
    era: EraId.ERA_8_BIT,
    minPlatform: PlatformId.C64,
    cpuCost: 2, ramCostKb: 1,
    difficulty: 10, originality: 15, audienceAppeal: 35,
    category: "raster",
    description: "Rainbow-like horizontal color bands generated by syncing color registers with the video beam refresh.",
    complexity: 15, visualImpact: 55,
    compatiblePlatforms: C64_ZX,
    synergyTags: ["raster", "copper", "palette"],
    researchRequired: false,
  },
  {
    id: "sine_scroller",
    name: "Sine Wave Scroller",
    era: EraId.ERA_8_BIT,
    minPlatform: PlatformId.C64,
    cpuCost: 4, ramCostKb: 2,
    difficulty: 15, originality: 20, audienceAppeal: 40,
    category: "pixel_trick",
    description: "Text scrolltext where each character or vertical line's height fluctuates based on a precalculated trigonometric sine lookup table.",
    complexity: 22, visualImpact: 45,
    compatiblePlatforms: C64_ZX,
    synergyTags: ["trig", "easing", "palette"],
    researchRequired: false,
  },
  {
    id: "starfield_2d",
    name: "2D Parallax Starfield",
    era: EraId.ERA_8_BIT,
    minPlatform: PlatformId.ZX_SPECTRUM,
    cpuCost: 3, ramCostKb: 1,
    difficulty: 12, originality: 12, audienceAppeal: 38,
    category: "vector",
    description: "Classic flying star simulation where multiple layers of pixels move at different speeds to simulate 3D space.",
    complexity: 12, visualImpact: 50,
    compatiblePlatforms: C64_ZX,
    synergyTags: ["vector", "parallax", "asm"],
    researchRequired: false,
  },
  {
    id: "twister",
    name: "Intertwining Twister (A-ST/Amiga)",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.ATARI_ST,
    cpuCost: 15, ramCostKb: 16,
    difficulty: 45, originality: 55, audienceAppeal: 70,
    category: "pixel_trick",
    description: "A twisting, ribbon-like 3D column displaying color shades on its rotating facets.",
    complexity: 55, visualImpact: 72,
    compatiblePlatforms: AMIGA_ST,
    synergyTags: ["blitter", "palette", "copper"],
    researchRequired: true,
  },
  {
    id: "animated_plasma",
    name: "Trigonometric Sine Plasma",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.AMIGA_500,
    cpuCost: 20, ramCostKb: 32,
    difficulty: 30, originality: 35, audienceAppeal: 65,
    category: "procedural",
    description: "Psychedelic evolving organic patterns computed by evaluating layered high-speed sine/cosine equations across the entire raster map.",
    complexity: 40, visualImpact: 70,
    compatiblePlatforms: AMIGA_ALL,
    synergyTags: ["trig", "palette", "procedural"],
    researchRequired: false,
  },
  {
    id: "vector_cube",
    name: "Flat Shaded Vector Cube",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.AMIGA_500,
    cpuCost: 18, ramCostKb: 8,
    difficulty: 35, originality: 40, audienceAppeal: 60,
    category: "vector",
    description: "Real-time 3D rotation of coordinate vertices, projected into screen space and rendered with filled solid colors.",
    complexity: 45, visualImpact: 58,
    compatiblePlatforms: AMIGA_ALL,
    synergyTags: ["vector", "fixed-point", "asm"],
    researchRequired: true,
  },
  {
    id: "pixel_fire",
    name: "Nostalgic Doom Fire Screen",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.PC_386,
    cpuCost: 12, ramCostKb: 64,
    difficulty: 20, originality: 25, audienceAppeal: 62,
    category: "procedural",
    description: "An organic combustion effect created by blending and shifting pixel indices upward with a small pseudo-random dampener.",
    complexity: 28, visualImpact: 68,
    compatiblePlatforms: PC_DAWN_PLUS,
    synergyTags: ["procedural", "palette"],
    researchRequired: false,
  },
  // --- PC ERA ---
  {
    id: "chunky_to_planar",
    name: "Chunky-to-Planar Subroutines",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.AMIGA_1200,
    cpuCost: 8, ramCostKb: 12,
    difficulty: 50, originality: 45, audienceAppeal: 50,
    category: "pixel_trick",
    description: "Highly optimized assembly code that converts byte-per-pixel buffers into multi-bitplane structures required by Amiga display chips.",
    complexity: 60, visualImpact: 30,
    compatiblePlatforms: [PlatformId.AMIGA_1200, PlatformId.AMIGA_500],
    synergyTags: ["blitter", "asm", "cycle-exact"],
    researchRequired: true,
  },
  {
    id: "texture_mapper",
    name: "Fast Poly Texture Mapping",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_486,
    cpuCost: 50, ramCostKb: 128,
    difficulty: 65, originality: 70, audienceAppeal: 82,
    category: "vector",
    description: "Drawing bitmaps onto 3D polygon structures using lightning-fast linear scanlines containing interpolated coordinates.",
    complexity: 70, visualImpact: 80,
    compatiblePlatforms: PC_DAWN_PLUS,
    synergyTags: ["vector", "fixed-point"],
    researchRequired: true,
  },
  {
    id: "tunnel_effect",
    name: "Precalculated Virtual Tunnel",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_386,
    cpuCost: 16, ramCostKb: 256,
    difficulty: 30, originality: 48, audienceAppeal: 74,
    category: "procedural",
    description: "Dizzying infinite cylinder visualization achieved using look-up tables mapping coordinates containing angle and distance.",
    complexity: 38, visualImpact: 76,
    compatiblePlatforms: PC_DAWN_PLUS,
    synergyTags: ["trig", "palette", "procedural"],
    researchRequired: true,
  },
  {
    id: "voxel_hills",
    name: "Voxel Heightfield Landscapes",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_486,
    cpuCost: 120, ramCostKb: 512,
    difficulty: 75, originality: 80, audienceAppeal: 85,
    category: "rendering",
    description: "Majestic volumetric mountain ranges rendered with raycasting heights from a 2D canvas elevation and color map (inspired by Comanche).",
    complexity: 78, visualImpact: 88,
    compatiblePlatforms: PC_DAWN_PLUS,
    synergyTags: ["raycast", "heightfield", "fixed-point"],
    researchRequired: true,
  },
  {
    id: "gouraud_shading",
    name: "Gouraud Polygon Pipeline",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_486,
    cpuCost: 40, ramCostKb: 128,
    difficulty: 55, originality: 50, audienceAppeal: 72,
    category: "vector",
    description: "Smooth 3D color gradients computed by interpolating lighting normals across the entire face of triangular mesh models.",
    complexity: 60, visualImpact: 70,
    compatiblePlatforms: PC_DAWN_PLUS,
    synergyTags: ["vector", "fixed-point"],
    researchRequired: true,
  },
  {
    id: "metaballs_2d",
    name: "2D Force-Field Metaballs",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_386,
    cpuCost: 35, ramCostKb: 64,
    difficulty: 40, originality: 45, audienceAppeal: 68,
    category: "procedural",
    description: "Liquid-like gooey blobs that merge elegantly, rendered by summing magnetic force vectors from moving control charges at each pixel.",
    complexity: 45, visualImpact: 72,
    compatiblePlatforms: PC_DAWN_PLUS,
    synergyTags: ["procedural", "palette", "novel"],
    researchRequired: true,
  },
  // --- MODERN SHADER ERA ---
  {
    id: "fractal_renderer",
    name: "Procedural Mandelbrot/Julia Zoomer",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM,
    cpuCost: 150, ramCostKb: 1024,
    difficulty: 50, originality: 45, audienceAppeal: 65,
    category: "rendering",
    description: "Endless exploration of complex numbers. Multiplies coordinates iteratively to output infinite crystalline structures.",
    complexity: 55, visualImpact: 80,
    compatiblePlatforms: PC_PENTIUM_PLUS,
    synergyTags: ["procedural", "sdf", "novel"],
    researchRequired: true,
  },
  {
    id: "raymarching_3d",
    name: "3D Signed Distance Fields Raymarching",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM_III,
    cpuCost: 450, ramCostKb: 2048,
    difficulty: 90, originality: 95, audienceAppeal: 96,
    category: "rendering",
    description: "Cutting-edge pixel evaluation where light vectors march forward along signed distance functions to render complex geometry on screen.",
    complexity: 95, visualImpact: 96,
    compatiblePlatforms: PC_PIII,
    synergyTags: ["sdf", "procedural", "novel"],
    researchRequired: true,
  },
  {
    id: "procedural_synth",
    name: "64KB Realtime Music Synth",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM_II,
    cpuCost: 80, ramCostKb: 12,
    difficulty: 80, originality: 90, audienceAppeal: 88,
    category: "procedural",
    description: "Avoid raw wave audio entirely. Generate sweeping bass, drums, and synthesizers mathematically in a few hundred bytes of code.",
    complexity: 85, visualImpact: 20,
    compatiblePlatforms: PC_PII_PLUS,
    synergyTags: ["procedural-audio", "sync", "asm"],
    researchRequired: true,
  },
  {
    id: "cloth_physics",
    name: "Mass-Spring Cloth Physics Engine",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM_II,
    cpuCost: 160, ramCostKb: 1024,
    difficulty: 72, originality: 78, audienceAppeal: 84,
    category: "vector",
    description: "Simulating gravity, tensions, and wind on a sheet of vertices linked via Verlet integration springs.",
    complexity: 78, visualImpact: 80,
    compatiblePlatforms: PC_PII_PLUS,
    synergyTags: ["vector", "fixed-point", "physics"],
    researchRequired: true,
  }
];
'''
Path("sim/data/demoEffects.ts").write_text(EFFECTS_SRC, encoding="utf-8")
print("  [OK] Rewrote sim/data/demoEffects.ts with all 17 entries")

# ============================================================================
# Step 2: append helper functions to scoring.ts
# ============================================================================

SCORING_PATH = Path("sim/domain/scoring.ts")
src = SCORING_PATH.read_text(encoding="utf-8")

# Append at the end of the file.
APPENDIX = '''

// ---------------------------------------------------------------------------
// Top-level summary builder
// ---------------------------------------------------------------------------

/**
 * One-call builder that returns a complete `DemoSummary` — the
 * breakdown, the awards, the procedural judge comments, and the
 * competition predictions at the upcoming parties. Filter the parties
 * to those the production can legally enter (platformFocus match).
 */
export function generateDemoSummary(input: ScoringInput): DemoSummary {
  const breakdown = calculateScoreBreakdown(input);
  const awards = awardsForBreakdown(breakdown, input.creation);
  const judgeComments = judgeCommentsFor(breakdown, input.creation);
  const compatibleParties = input.upcomingParties.filter((p) => {
    if (p.platformFocus === "all") return true;
    return p.platformFocus === input.creation.platform;
  });
  const predictions = predictPlacements(breakdown, {
    ...input,
    upcomingParties: compatibleParties,
  });
  // Dev time from the same arithmetic the engine uses (so the report
  // and the breakdown agree).
  const baseMonths: Record<string, number> = {
    Short: 1, Medium: 2, Long: 4, Epic: 7,
  };
  const dirDef = ARTISTIC_DIRECTION_DEFS[input.creation.artisticDirection];
  const focusMultiplier: Record<string, number> = {
    Speed: 0.5, Balanced: 1.0, "Visual Quality": 1.6,
  };
  const devTimeMonths = Math.max(
    1,
    Math.round(
      (baseMonths[input.creation.duration] ?? 2) *
        dirDef.devTimeMultiplier *
        (focusMultiplier[input.creation.optimizationFocus] ?? 1)
    )
  );
  // Build a Production-shaped stub. The caller (App.tsx) replaces this
  // with the fully-event-sourced Production once it dispatches the
  // DemoCompiled event. The stub carries the extra fields the report
  // needs (musicTrackStoredName, artisticDirection) that are not on
  // the legacy Production type.
  const totalScore = breakdown.overall;
  const stub = {
    id: `prod_report_${Date.now()}`,
    name: input.creation.name,
    year: 0,
    month: 0,
    type: input.creation.type,
    platform: input.creation.platform,
    groupName: "",
    effects: input.creation.effects,
    codingEffort: input.creation.effort.coding,
    artEffort: input.creation.effort.art,
    musicEffort: input.creation.effort.music,
    optimizationLevel: 3,
    compressionLevel: 3,
    sizeB: 0,
    scoreTechnical: breakdown.programming,
    scoreAesthetic: breakdown.graphics,
    scoreAudio: breakdown.music,
    scoreOriginality: breakdown.originality,
    totalScore,
    reputationGained: Math.round(totalScore / 3),
    // Ad-hoc extras (not in Production type) so the modal can show them.
    musicTrackStoredName: input.creation.musicTrackStoredName,
    artisticDirection: input.creation.artisticDirection,
    optimizationFocus: input.creation.optimizationFocus,
    duration: input.creation.duration,
  } as unknown as DemoSummary["production"];
  return {
    production: stub,
    breakdown,
    predictions,
    awards,
    judgeComments,
    developmentTimeMonths: devTimeMonths,
  };
}

/**
 * Era- and platform-compatibility filter. Returns the subset of
 * `effects` that the player can legally select for `platform` at the
 * given `currentYear`. Used by the UI to disable incompatible effect
 * checkboxes and by the engine to reject mismatched creations.
 */
export function compatibleEffects(
  effects: DemoEffect[],
  platform: PlatformId,
  currentYear: number
): DemoEffect[] {
  const eraStartYear: Record<string, number> = {
    ERA_8_BIT: 1985,
    ERA_16_BIT: 1990,
    ERA_PC_DAWN: 1996,
    ERA_3D_SHADER: 2001,
  };
  return effects.filter((e) => {
    if (!e.compatiblePlatforms.includes(platform)) return false;
    const startYear = eraStartYear[e.era] ?? 1985;
    return currentYear >= startYear;
  });
}
'''

SCORING_PATH.write_text(src + APPENDIX, encoding="utf-8")
print("  [OK] Appended generateDemoSummary + compatibleEffects to scoring.ts")

print(f"\nAll edits applied.")
