/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * DEMO_EFFECTS catalogue — moved verbatim from src/data.ts.
 * Static lookup of effect complexity / cost params; pure data only.
 */

import { DemoEffect, EraId, PlatformId } from "@packages/types";

export const DEMO_EFFECTS: DemoEffect[] = [
  // --- 8-BIT ERA ---
  {
    id: "raster_bars",
    name: "Raster Bars / Copper Bars",
    era: EraId.ERA_8_BIT,
    minPlatform: PlatformId.C64,
    cpuCost: 2, ramCostKb: 1,
    difficulty: 10, originality: 15, audienceAppeal: 35,
    category: "raster",
    description: "Rainbow-like horizontal color bands generated by syncing color registers with the video beam refresh."
  },
  {
    id: "sine_scroller",
    name: "Sine Wave Scroller",
    era: EraId.ERA_8_BIT,
    minPlatform: PlatformId.C64,
    cpuCost: 4, ramCostKb: 2,
    difficulty: 15, originality: 20, audienceAppeal: 40,
    category: "pixel_trick",
    description: "Text scrolltext where each character or vertical line's height fluctuates based on a precalculated trigonometric sine lookup table."
  },
  {
    id: "starfield_2d",
    name: "2D Parallax Starfield",
    era: EraId.ERA_8_BIT,
    minPlatform: PlatformId.ZX_SPECTRUM,
    cpuCost: 3, ramCostKb: 1,
    difficulty: 12, originality: 12, audienceAppeal: 38,
    category: "vector",
    description: "Classic flying star simulation where multiple layers of pixels move at different speeds to simulate 3D space."
  },
  {
    id: "twister",
    name: "Intertwining Twister (A-ST/Amiga)",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.ATARI_ST,
    cpuCost: 15, ramCostKb: 16,
    difficulty: 45, originality: 55, audienceAppeal: 70,
    category: "pixel_trick",
    description: "A twisting, ribbon-like 3D column displaying color shades on its rotating facets."
  },
  {
    id: "animated_plasma",
    name: "Trigonometric Sine Plasma",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.AMIGA_500,
    cpuCost: 20, ramCostKb: 32,
    difficulty: 30, originality: 35, audienceAppeal: 65,
    category: "procedural",
    description: "Psychedelic evolving organic patterns computed by evaluating layered high-speed sine/cosine equations across the entire raster map."
  },
  {
    id: "vector_cube",
    name: "Flat Shaded Vector Cube",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.AMIGA_500,
    cpuCost: 18, ramCostKb: 8,
    difficulty: 35, originality: 40, audienceAppeal: 60,
    category: "vector",
    description: "Real-time 3D rotation of coordinate vertices, projected into screen space and rendered with filled solid colors."
  },
  {
    id: "pixel_fire",
    name: "Nostalgic Doom Fire Screen",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.PC_386,
    cpuCost: 12, ramCostKb: 64,
    difficulty: 20, originality: 25, audienceAppeal: 62,
    category: "procedural",
    description: "An organic combustion effect created by blending and shifting pixel indices upward with a small pseudo-random dampener."
  },
  // --- PC ERA ---
  {
    id: "chunky_to_planar",
    name: "Chunky-to-Planar Subroutines",
    era: EraId.ERA_16_BIT,
    minPlatform: PlatformId.AMIGA_1200,
    cpuCost: 8, ramCostKb: 12,
    difficulty: 50, originality: 45, audienceAppeal: 50,
    category: "pixel_trick",
    description: "Highly optimized assembly code that converts byte-per-pixel buffers into multi-bitplane structures required by Amiga display chips."
  },
  {
    id: "texture_mapper",
    name: "Fast Poly Texture Mapping",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_486,
    cpuCost: 50, ramCostKb: 128,
    difficulty: 65, originality: 70, audienceAppeal: 82,
    category: "vector",
    description: "Drawing bitmaps onto 3D polygon structures using lightning-fast linear scanlines containing interpolated coordinates."
  },
  {
    id: "tunnel_effect",
    name: "Precalculated Virtual Tunnel",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_386,
    cpuCost: 16, ramCostKb: 256,
    difficulty: 30, originality: 48, audienceAppeal: 74,
    category: "procedural",
    description: "Dizzying infinite cylinder visualization achieved using look-up tables mapping coordinates containing angle and distance."
  },
  {
    id: "voxel_hills",
    name: "Voxel Heightfield Landscapes",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_486,
    cpuCost: 120, ramCostKb: 512,
    difficulty: 75, originality: 80, audienceAppeal: 85,
    category: "rendering",
    description: "Majestic volumetric mountain ranges rendered with raycasting heights from a 2D canvas elevation and color map (inspired by Comanche)."
  },
  {
    id: "gouraud_shading",
    name: "Gouraud Polygon Pipeline",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_486,
    cpuCost: 40, ramCostKb: 128,
    difficulty: 55, originality: 50, audienceAppeal: 72,
    category: "vector",
    description: "Smooth 3D color gradients computed by interpolating lighting normals across the entire face of triangular mesh models."
  },
  {
    id: "metaballs_2d",
    name: "2D Force-Field Metaballs",
    era: EraId.ERA_PC_DAWN,
    minPlatform: PlatformId.PC_386,
    cpuCost: 35, ramCostKb: 64,
    difficulty: 40, originality: 45, audienceAppeal: 68,
    category: "procedural",
    description: "Liquid-like gooey blobs that merge elegantly, rendered by summing magnetic force vectors from moving control charges at each pixel."
  },
  // --- MODERN SHADER ERA ---
  {
    id: "fractal_renderer",
    name: "Procedural Mandelbrot/Julia Zoomer",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM,
    cpuCost: 150, ramCostKb: 1024,
    difficulty: 50, originality: 45, audienceAppeal: 65,
    category: "rendering",
    description: "Endless exploration of complex numbers. Multiplies coordinates iteratively to output infinite crystalline structures."
  },
  {
    id: "raymarching_3d",
    name: "3D Signed Distance Fields Raymarching",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM_III,
    cpuCost: 450, ramCostKb: 2048,
    difficulty: 90, originality: 95, audienceAppeal: 96,
    category: "rendering",
    description: "Cutting-edge pixel evaluation where light vectors march forward along signed distance functions to render complex geometry on screen."
  },
  {
    id: "procedural_synth",
    name: "64KB Realtime Music Synth",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM_II,
    cpuCost: 80, ramCostKb: 12,
    difficulty: 80, originality: 90, audienceAppeal: 88,
    category: "procedural",
    description: "Avoid raw wave audio entirely. Generate sweeping bass, drums, and synthesizers mathematically in a few hundred bytes of code."
  },
  {
    id: "cloth_physics",
    name: "Mass-Spring Cloth Physics Engine",
    era: EraId.ERA_3D_SHADER,
    minPlatform: PlatformId.PC_PENTIUM_II,
    cpuCost: 160, ramCostKb: 1024,
    difficulty: 72, originality: 78, audienceAppeal: 84,
    category: "vector",
    description: "Simulating gravity, tensions, and wind on a sheet of vertices linked via Verlet integration springs."
  }
];
